openapi: 3.0.0
components:
  schemas:
    message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Example message'
    error_message:
      type: object
      required:
        - title
        - detail
        - status
        - requestId
      properties:
        title:
          type: string
          example: 'Error'
        detail:
          type: string
          example: 'Example error message'
        status:
          type: integer
          example: 400
        details:
          type: array
        requestId:
          type: string
          example: '123456'
