// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package common

// ErrorMessage defines the model for error_message.
type ErrorMessage struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Message defines the model for message.
type Message struct {
	Message *string `json:"message,omitempty"`
}
